# This workflow demonstrates branch protection setup
# Note: This is a reference file - actual branch protection must be configured in GitHub repository settings

name: Branch Protection Reference

# This workflow doesn't run automatically - it's for reference only
on:
  workflow_dispatch:

jobs:
  reference:
    runs-on: ubuntu-latest
    steps:
      - name: Branch Protection Setup Guide
        run: |
          echo "Branch Protection Configuration Guide"
          echo "====================================="
          echo ""
          echo "To set up branch protection for main/master branch:"
          echo "1. Go to Settings > Branches"
          echo "2. Add rule for main/master branch"
          echo "3. Enable the following options:"
          echo "   - Require a pull request before merging"
          echo "   - Require status checks to pass before merging"
          echo "   - Require branches to be up to date before merging"
          echo "   - Require conversation resolution before merging"
          echo "   - Require signed commits"
          echo "   - Require linear history"
          echo ""
          echo "Required status checks:"
          echo "- ci (from .github/workflows/ci.yml)"
          echo ""
          echo "This ensures all PRs go through the CI pipeline"
