name: CI Pipeline

on:
  pull_request:
    branches: [ main, master ]
    types: [ opened, synchronize, reopened ]
  push:
    branches: [ main, master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [15.5.1]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: Complete-Coding-Challenge-Z/codebase/rdicidr-0.1.0/package-lock.json
        
    - name: Install dependencies
      working-directory: Complete-Coding-Challenge-Z/codebase/rdicidr-0.1.0
      run: npm ci
      
    - name: Run ESLint
      working-directory: Complete-Coding-Challenge-Z/codebase/rdicidr-0.1.0
      run: npm run lint
      
    - name: Run Prettier check
      working-directory: Complete-Coding-Challenge-Z/codebase/rdicidr-0.1.0
      run: npm run prettier
      
    - name: Run tests
      working-directory: Complete-Coding-Challenge-Z/codebase/rdicidr-0.1.0
      run: CI=true npm run test -- --watchAll=false --coverage --passWithNoTests
      
    - name: Build application
      working-directory: Complete-Coding-Challenge-Z/codebase/rdicidr-0.1.0
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: Complete-Coding-Challenge-Z/codebase/rdicidr-0.1.0/build/
        retention-days: 7
